#!/bin/bash

# 
# eject - 
# 
# v0.1   2007-05-21 - Morgan Aldridge <morgant@makkintosshu.com>
#                     Initial version.
# v0.2   2010-10-24 - Morgan Aldridge
#                     Minor cleanup. Automatically prepend /Volumes/ to volume name if omitted.
# 

# TO DO:
# - Verbose doesn't currently do anything.

# global variables
verbose=false
help=false

# print usage instructions (help)
function usage() {
	printf "Usage: eject [options] volume ...\n"
	printf "  -v		verbose output\n"
	printf "  -h		print these usage instructions\n"
}

# see if any arguments were passed in
if [ $# -gt 0 ]; then
	# if so, step through them all and process them
	while [ $# -gt 0 ]; do
		 # see if the user intended us to run in verbose mode
                if [ "$1" = "-v" ]; then
                        shift
                        verbose=true
                # see if the user requested help
                elif [ "$1" = "-h" ]; then
                        shift
                        help=true
                        usage
		else
                        # don't bother doing anything if the user requested help
                        if ! $help; then
				# try to detect whether the user prepended "/Volumes/" to the volume name
				if [ "${1:0:9}" = "/Volumes/" ]; then
					diskutil eject "$1"
				else
					diskutil eject "/Volumes/$1"
				fi
                        fi
                        shift
                fi
	done
else
	printf "No volumes were specified to be ejected.\n\n"
	usage
fi
